require 'money/bank/google_currency'

Money::Bank::GoogleCurrency.ttl_in_seconds = 3600

Money.default_bank = Money::Bank::GoogleCurrency.new

SUPPORTED_CURRENCIES = { 'ARS' => 'Argentine Peso (ARS)',
                         'AMD' => 'Armenian Dram (AMD)',
                         'AWG' => 'Aruban Florin (AWG)',
                         'AUD' => 'Australian Dollar (A$)',
                         'AZN' => 'Azerbaijani Manat (AZN)',
                         'BSD' => 'Bahamian Dollar (BSD)',
                         'BHD' => 'Bahraini Dinar (BHD)',
                         'BDT' => 'Bangladeshi Taka (BDT)',
                         'BBD' => 'Barbadian Dollar (BBD)',
                         'BYR' => 'Belarusian Ruble (BYR)',
                         'BZD' => 'Belize Dollar (BZD)',
                         'BMD' => 'Bermudan Dollar (BMD)',
                         'BTN' => 'Bhutanese Ngultrum (BTN)',
                         'BOB' => 'Bolivian Boliviano (BOB)',
                         'BAM' => 'Bosnia-Herzegovina Convertible Mark (BAM)',
                         'BWP' => 'Botswanan Pula (BWP)',
                         'BRL' => 'Brazilian Real (R$)',
                         'GBP' => 'British Pound Sterling (£)',
                         'BND' => 'Brunei Dollar (BND)',
                         'BGN' => 'Bulgarian Lev (BGN)',
                         'BIF' => 'Burundian Franc (BIF)',
                         'XOF' => 'CFA Franc BCEAO (CFA)',
                         'XAF' => 'CFA Franc BEAC (FCFA)',
                         'XPF' => 'CFP Franc (CFPF)',
                         'CNH' => 'CNH (CNH)',
                         'KHR' => 'Cambodian Riel (KHR)',
                         'CAD' => 'Canadian Dollar (CA$)',
                         'CVE' => 'Cape Verdean Escudo (CVE)',
                         'KYD' => 'Cayman Islands Dollar (KYD)',
                         'CLP' => 'Chilean Peso (CLP)',
                         'CLF' => 'Chilean Unit of Account (UF) (CLF)',
                         'CNY' => 'Chinese Yuan (CN¥)',
                         'COP' => 'Colombian Peso (COP)',
                         'KMF' => 'Comorian Franc (KMF)',
                         'CDF' => 'Congolese Franc (CDF)',
                         'CRC' => 'Costa Rican Colón (CRC)',
                         'HRK' => 'Croatian Kuna (HRK)',
                         'CUP' => 'Cuban Peso (CUP)',
                         'CZK' => 'Czech Republic Koruna (CZK)',
                         'DKK' => 'Danish Krone (DKK)',
                         'DJF' => 'Djiboutian Franc (DJF)',
                         'DOP' => 'Dominican Peso (DOP)',
                         'XCD' => 'East Caribbean Dollar (EC$)',
                         'EGP' => 'Egyptian Pound (EGP)',
                         'ERN' => 'Eritrean Nakfa (ERN)',
                         'ETB' => 'Ethiopian Birr (ETB)',
                         'EUR' => 'Euro (€)',
                         'FKP' => 'Falkland Islands Pound (FKP)',
                         'FJD' => 'Fijian Dollar (FJD)',
                         'FIM' => 'Finnish Markka (FIM)',
                         'FRF' => 'French Franc (FRF)',
                         'GMD' => 'Gambian Dalasi (GMD)',
                         'GEL' => 'Georgian Lari (GEL)',
                         'DEM' => 'German Mark (DEM)',
                         'GHS' => 'Ghanaian Cedi (GHS)',
                         'GIP' => 'Gibraltar Pound (GIP)',
                         'GTQ' => 'Guatemalan Quetzal (GTQ)',
                         'GNF' => 'Guinean Franc (GNF)',
                         'GYD' => 'Guyanaese Dollar (GYD)',
                         'HTG' => 'Haitian Gourde (HTG)',
                         'HNL' => 'Honduran Lempira (HNL)',
                         'HKD' => 'Hong Kong Dollar (HK$)',
                         'HUF' => 'Hungarian Forint (HUF)',
                         'ISK' => 'Icelandic Króna (ISK)',
                         'INR' => 'Indian Rupee (Rs.)',
                         'IDR' => 'Indonesian Rupiah (IDR)',
                         'IRR' => 'Iranian Rial (IRR)',
                         'IQD' => 'Iraqi Dinar (IQD)',
                         'IEP' => 'Irish Pound (IEP)',
                         'ILS' => 'Israeli New Sheqel (₪)',
                         'ITL' => 'Italian Lira (ITL)',
                         'JMD' => 'Jamaican Dollar (JMD)',
                         'JPY' => 'Japanese Yen (¥)',
                         'JOD' => 'Jordanian Dinar (JOD)',
                         'KZT' => 'Kazakhstani Tenge (KZT)',
                         'KES' => 'Kenyan Shilling (KES)',
                         'KWD' => 'Kuwaiti Dinar (KWD)',
                         'KGS' => 'Kyrgystani Som (KGS)',
                         'LAK' => 'Laotian Kip (LAK)',
                         'LVL' => 'Latvian Lats (LVL)',
                         'LBP' => 'Lebanese Pound (LBP)',
                         'LSL' => 'Lesotho Loti (LSL)',
                         'LRD' => 'Liberian Dollar (LRD)',
                         'LYD' => 'Libyan Dinar (LYD)',
                         'LTL' => 'Lithuanian Litas (LTL)',
                         'MOP' => 'Macanese Pataca (MOP)',
                         'MKD' => 'Macedonian Denar (MKD)',
                         'MGA' => 'Malagasy Ariary (MGA)',
                         'MWK' => 'Malawian Kwacha (MWK)',
                         'MYR' => 'Malaysian Ringgit (MYR)',
                         'MVR' => 'Maldivian Rufiyaa (MVR)',
                         'MRO' => 'Mauritanian Ouguiya (MRO)',
                         'MUR' => 'Mauritian Rupee (MUR)',
                         'MXN' => 'Mexican Peso (MX$)',
                         'MDL' => 'Moldovan Leu (MDL)',
                         'MNT' => 'Mongolian Tugrik (MNT)',
                         'MAD' => 'Moroccan Dirham (MAD)',
                         'MZN' => 'Mozambican Metical (MZN)',
                         'MMK' => 'Myanma Kyat (MMK)',
                         'NAD' => 'Namibian Dollar (NAD)',
                         'NPR' => 'Nepalese Rupee (NPR)',
                         'ANG' => 'Netherlands Antillean Guilder (ANG)',
                         'TWD' => 'New Taiwan Dollar (NT$)',
                         'NZD' => 'New Zealand Dollar (NZ$)',
                         'NIO' => 'Nicaraguan Córdoba (NIO)',
                         'NGN' => 'Nigerian Naira (NGN)',
                         'KPW' => 'North Korean Won (KPW)',
                         'NOK' => 'Norwegian Krone (NOK)',
                         'OMR' => 'Omani Rial (OMR)',
                         'PKG' => 'PKG (PKG)',
                         'PKR' => 'Pakistani Rupee (PKR)',
                         'PAB' => 'Panamanian Balboa (PAB)',
                         'PGK' => 'Papua New Guinean Kina (PGK)',
                         'PYG' => 'Paraguayan Guarani (PYG)',
                         'PEN' => 'Peruvian Nuevo Sol (PEN)',
                         'PHP' => 'Philippine Peso (Php)',
                         'PLN' => 'Polish Zloty (PLN)',
                         'QAR' => 'Qatari Rial (QAR)',
                         'RON' => 'Romanian Leu (RON)',
                         'RUB' => 'Russian Ruble (RUB)',
                         'RWF' => 'Rwandan Franc (RWF)',
                         'SHP' => 'Saint Helena Pound (SHP)',
                         'SVC' => 'Salvadoran Colón (SVC)',
                         'WST' => 'Samoan Tala (WST)',
                         'SAR' => 'Saudi Riyal (SAR)',
                         'RSD' => 'Serbian Dinar (RSD)',
                         'SCR' => 'Seychellois Rupee (SCR)',
                         'SLL' => 'Sierra Leonean Leone (SLL)',
                         'SGD' => 'Singapore Dollar (SGD)',
                         'SBD' => 'Solomon Islands Dollar (SBD)',
                         'SOS' => 'Somali Shilling (SOS)',
                         'ZAR' => 'South African Rand (ZAR)',
                         'KRW' => 'South Korean Won (₩)',
                         'XDR' => 'Special Drawing Rights (XDR)',
                         'LKR' => 'Sri Lankan Rupee (LKR)',
                         'SDG' => 'Sudanese Pound (SDG)',
                         'SRD' => 'Surinamese Dollar (SRD)',
                         'SZL' => 'Swazi Lilangeni (SZL)',
                         'SEK' => 'Swedish Krona (SEK)',
                         'CHF' => 'Swiss Franc (CHF)',
                         'SYP' => 'Syrian Pound (SYP)',
                         'STD' => 'São Tomé and Príncipe Dobra (STD)',
                         'TJS' => 'Tajikistani Somoni (TJS)',
                         'TZS' => 'Tanzanian Shilling (TZS)',
                         'THB' => 'Thai Baht (฿)',
                         'TOP' => 'Tongan Paʻanga (TOP)',
                         'TTD' => 'Trinidad and Tobago Dollar (TTD)',
                         'TND' => 'Tunisian Dinar (TND)',
                         'TRY' => 'Turkish Lira (TRY)',
                         'TMT' => 'Turkmenistani Manat (TMT)',
                         'USD' => 'US Dollar ($)',
                         'UGX' => 'Ugandan Shilling (UGX)',
                         'UAH' => 'Ukrainian Hryvnia (UAH)',
                         'AED' => 'United Arab Emirates Dirham (AED)',
                         'UYU' => 'Uruguayan Peso (UYU)',
                         'UZS' => 'Uzbekistan Som (UZS)',
                         'VUV' => 'Vanuatu Vatu (VUV)',
                         'VEF' => 'Venezuelan Bolívar (VEF)',
                         'VND' => 'Vietnamese Dong (₫)',
                         'YER' => 'Yemeni Rial (YER)',
                         'ZMK' => 'Zambian Kwacha (1968-2012) (ZMK)',
                         'ZMW' => 'Zambian Kwacha (ZMW)',
                         'ZWL' => 'Zimbabwean Dollar (2009) (ZWL)'
}

COUNTRY_CURRENCIES = { 'AD' => 'EUR', 'AE' => 'AED', 'AF' => 'AFN', 'AG' => 'XCD', 'AI' => 'XCD', 'AL' => 'ALL',
                       'AM' => 'AMD', 'AO' => 'AOA', 'AQ' => 'AUD', 'AR' => 'ARS', 'AS' => 'USD', 'AT' => 'EUR',
                       'AU' => 'AUD', 'AW' => 'AWG', 'AX' => 'FIM', 'AZ' => 'AZN', 'BA' => 'BAM', 'BB' => 'BBD',
                       'BD' => 'BDT', 'BE' => 'EUR', 'BF' => 'XOF', 'BG' => 'BGN', 'BH' => 'BHD', 'BI' => 'BIF',
                       'BJ' => 'XOF', 'BL' => 'EUR', 'BM' => 'BMD', 'BN' => 'BND', 'BO' => 'BOB', 'BQ' => 'USD',
                       'BR' => 'BRL', 'BS' => 'BSD', 'BT' => 'BTN', 'BV' => 'NOK', 'BW' => 'BWP', 'BY' => 'BYR',
                       'BZ' => 'BZD', 'CA' => 'CAD', 'CC' => 'AUD', 'CD' => 'CDF', 'CF' => 'XAF', 'CG' => 'XAF',
                       'CH' => 'CHF', 'CI' => 'XOF', 'CK' => 'NZD', 'CL' => 'CLP', 'CM' => 'XAF', 'CN' => 'CNY',
                       'CO' => 'COP', 'CR' => 'CRC', 'CU' => 'CUP', 'CV' => 'CVE', 'CW' => 'ANG', 'CX' => 'AUD',
                       'CY' => 'EUR', 'CZ' => 'CZK', 'DE' => 'EUR', 'DJ' => 'DJF', 'DK' => 'DKK', 'DM' => 'XCD',
                       'DO' => 'DOP', 'DZ' => 'DZD', 'EC' => 'USD', 'EE' => 'EEK', 'EG' => 'EGP', 'EH' => 'MAD',
                       'ER' => 'ETB', 'ES' => 'EUR', 'ET' => 'ETB', 'FI' => 'EUR', 'FJ' => 'FJD', 'FK' => 'FKP',
                       'FM' => 'USD', 'FO' => 'DKK', 'FR' => 'EUR', 'GA' => 'XAF', 'GB' => 'GBP', 'GD' => 'XCD',
                       'GE' => 'GEL', 'GF' => 'EUR', 'GG' => 'GGP', 'GH' => 'GHS', 'GI' => 'GIP', 'GL' => 'DKK',
                       'GM' => 'GMD', 'GN' => 'GNF', 'GP' => 'EUR', 'GQ' => 'XAF', 'GR' => 'EUR', 'GS' => 'GBP',
                       'GT' => 'GTQ', 'GU' => 'USD', 'GW' => 'XOF', 'GY' => 'GYD', 'HK' => 'HKD', 'HM' => 'AUD',
                       'HN' => 'HNL', 'HR' => 'HRK', 'HT' => 'HTG', 'HU' => 'HUF', 'ID' => 'IDR', 'IE' => 'EUR',
                       'IL' => 'ILS', 'IM' => 'IMP', 'IN' => 'INR', 'IO' => 'USD', 'IQ' => 'IQD', 'IR' => 'IRR',
                       'IS' => 'ISK', 'IT' => 'EUR', 'JE' => 'JEP', 'JM' => 'JMD', 'JO' => 'JOD', 'JP' => 'JPY',
                       'KE' => 'KES', 'KG' => 'KGS', 'KH' => 'KHR', 'KI' => 'AUD', 'KM' => 'KMF', 'KN' => 'XCD',
                       'KP' => 'KRW', 'KR' => 'KPW', 'KW' => 'KWD', 'KY' => 'KYD', 'KZ' => 'KZT', 'LA' => 'LAK',
                       'LB' => 'LBP', 'LC' => 'XCD', 'LI' => 'CHF', 'LK' => 'LKR', 'LR' => 'LRD', 'LS' => 'LSL',
                       'LT' => 'LTL', 'LU' => 'EUR', 'LV' => 'LVL', 'LY' => 'LYD', 'MA' => 'MAD', 'MC' => 'EUR',
                       'MD' => 'MDL', 'ME' => 'EUR', 'MF' => 'EUR', 'MG' => 'MGA', 'MH' => 'USD', 'MK' => 'MKD',
                       'ML' => 'XOF', 'MM' => 'MMK', 'MN' => 'MNT', 'MO' => 'MOP', 'MP' => 'USD', 'MQ' => 'EUR',
                       'MR' => 'MRO', 'MS' => 'XCD', 'MT' => 'EUR', 'MU' => 'MUR', 'MV' => 'MVR', 'MW' => 'MWK',
                       'MX' => 'MXN', 'MY' => 'MYR', 'MZ' => 'MZN', 'NA' => 'NAD', 'NC' => 'XPF', 'NE' => 'XOF',
                       'NF' => 'AUD', 'NG' => 'NGN', 'NI' => 'NIO', 'NL' => 'EUR', 'NO' => 'NOK', 'NP' => 'NPR',
                       'NR' => 'AUD', 'NU' => 'NZD', 'NZ' => 'NZD', 'OM' => 'OMR', 'PA' => 'PAB', 'PE' => 'PEN',
                       'PF' => 'XPF', 'PG' => 'PGK', 'PH' => 'PHP', 'PK' => 'PKR', 'PL' => 'PLN', 'PM' => 'EUR',
                       'PN' => 'NZD', 'PR' => 'USD', 'PS' => 'JOD', 'PT' => 'EUR', 'PW' => 'USD', 'PY' => 'PYG',
                       'QA' => 'QAR', 'RE' => 'EUR', 'RO' => 'RON', 'RS' => 'RSD', 'RU' => 'RUB', 'RW' => 'RWF',
                       'SA' => 'SAR', 'SB' => 'SBD', 'SC' => 'SCR', 'SD' => 'SDG', 'SE' => 'SEK', 'SG' => 'SGD',
                       'SH' => 'SHP', 'SI' => 'EUR', 'SJ' => 'NOK', 'SK' => 'SKK', 'SL' => 'SLL', 'SM' => 'EUR',
                       'SN' => 'XOF', 'SO' => 'SOS', 'SR' => 'SRD', 'SS' => 'SSP', 'ST' => 'STD', 'SV' => 'SVC',
                       'SX' => 'ANG', 'SY' => 'SYP', 'SZ' => 'CHF', 'TC' => 'USD', 'TD' => 'XAF', 'TF' => 'EUR',
                       'TG' => 'XOF', 'TH' => 'THB', 'TJ' => 'TJS', 'TK' => 'NZD', 'TL' => 'IDR', 'TM' => 'TMM',
                       'TN' => 'TND', 'TO' => 'TOP', 'TR' => 'TRY', 'TT' => 'TTD', 'TV' => 'TVD', 'TW' => 'TWD',
                       'TZ' => 'TZS', 'UA' => 'UAH', 'UG' => 'UGX', 'UM' => 'USD', 'US' => 'USD', 'UY' => 'UYU',
                       'UZ' => 'UZS', 'VA' => 'EUR', 'VC' => 'XCD', 'VE' => 'VEF', 'VG' => 'USD', 'VI' => 'USD',
                       'VN' => 'VND', 'VU' => 'VUV', 'WF' => 'XPF', 'WS' => 'WST', 'YE' => 'YER', 'YT' => 'EUR',
                       'ZA' => 'ZAR', 'ZM' => 'ZMW', 'ZW' => 'ZWD'
}